feat: added test coverage
NDVR-3536

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -3,6 +3,8 @@ on:
     secrets:
       GHCR_TOKEN:
         required: true
+      SONAR_TOKEN:
+        required: true
 env:
   GHCR_USER: ${{ vars.GHCR_USER }}
   GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
@@ -10,6 +12,9 @@ env:
   REPO_DEVOPS_BRANCH: main
   ECLINT_REPO: editorconfig-checker/editorconfig-checker
   ECLINT_VERSION: 2.7.2
+  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  SONAR_HOST_URL: https://sonarcloud.io
+  PROJECT_KEY: GiGInnovationLabs_${{ github.event.repository.name }}
 jobs:
   test:
     name: run tests
@@ -60,10 +65,78 @@ jobs:
         run: |
           ln -s /opt/hostedtoolcache/${{ env.ECLINT_REPO }}/${{ env.ECLINT_VERSION }}/linux-x64/bin/ec-linux-amd64 \
             /opt/hostedtoolcache/${{ env.ECLINT_REPO }}/${{ env.ECLINT_VERSION }}/linux-x64/bin/editorconfig-checker
-      - name: test
-        run: | 
+      - name: Lint
+        run: |
+          just lint
+      
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: 17
+          distribution: 'zulu'
+
+      - name: Cache SonarQube Cloud packages
+        uses: actions/cache@v4
+        with:
+          path: ~/.sonar/cache
+          key: ${{ runner.os }}-sonar
+          restore-keys: ${{ runner.os }}-sonar
+
+      - name: Cache SonarQube Cloud scanner
+        id: cache-sonar-scanner
+        uses: actions/cache@v4
+        with:
+          path: ~/.sonar/scanner
+          key: ${{ runner.os }}-sonar-scanner
+          restore-keys: ${{ runner.os }}-sonar-scanner
+
+      - name: Install Sonar Scanner Tool
+        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
+        run: |
+          mkdir -p ~/.sonar/scanner
+          dotnet tool update dotnet-sonarscanner --tool-path ~/.sonar/scanner
+
+      - name: Install Report Generator
+        run: |
+          mkdir -p ~/.reportgenerator
+          dotnet tool update dotnet-reportgenerator-globaltool --tool-path ~/.reportgenerator
+
+      - name: Run Tests and Generate Coverage Report
+        run: |
           dotnet tool restore
-          just test
+          dotnet test --logger trx --results-directory /tmp/test-report --filter "Category=Unit|Category=Component|Category=Integration" --collect:"XPlat Code Coverage"
+          ~/.reportgenerator/reportgenerator -reports:"/tmp/test-report/**/coverage.cobertura.xml" -targetdir:"coverage-report" -reporttypes:SonarQube
+
+      - name: Build and Analyze
+        env:
+          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          ~/.sonar/scanner/dotnet-sonarscanner begin /k:"$PROJECT_KEY" /o:"giginnovationlabs" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ env.SONAR_HOST_URL }}" /d:sonar.coverageReportPaths="coverage-report/SonarQube.xml"
+          dotnet build
+          ~/.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
+
+      - name: Install jq (for JSON parsing)
+        run: sudo apt-get install jq -y
+
+      - name: Check Quality Gate Status
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          PR_NUMBER=${{ github.event.pull_request.number }}
+          echo "Checking Quality Gate for Pull Request #$PR_NUMBER"
+
+          API_URL="https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECT_KEY&pullRequest=$PR_NUMBER"
+
+          # Fetch Quality Gate Status
+          STATUS=$(curl -s -u "$SONAR_TOKEN:" "$API_URL" | jq -r .projectStatus.status)
+          echo "Quality Gate Status for Pull Request #$PR_NUMBER: $STATUS"
+
+          if [ "$STATUS" != "OK" ]; then
+              echo "Quality Gate failed for Pull Request #$PR_NUMBER!"
+              exit 1
+          fi
+
       - id: hasTestReport
         if: ${{ always() }}
         run: |
